mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
mpirun -n 4  ~/lammps/build/lmp -in npt.lmpi
