mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
mpirun -n 32 ~/lammps/build/lmp -in npt.lmpi
